name: Build and Push Docker Images

on:
  workflow_dispatch:  # Allows you to manually trigger the action from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Set up QEMU for emulation
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push multi-arch images
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ${{ matrix.arch == 'arm64' && 'Dockerfile.aarch64' || 'Dockerfile' }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: chris230291/oscam-emu:latest