name: Sync Fork with Upstream and Build Docker Image

on:
  schedule:
    - cron: '0 0 * * 0'  # This will run the action weekly on Sundays at midnight
  workflow_dispatch:  # Allows you to manually trigger the action from the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures we fetch all history so we can make changes to any branch

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/linuxserver/docker-oscam.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream into your branch (Ignore specific files)
        run: |
          git checkout master  # or main, depending on your default branch
          git merge upstream/master --no-commit || echo "No changes to merge"
          if [ $? -eq 0 ]; then
            # Restore files if merge was successful
            git restore --staged README.md
            git checkout -- README.md
            git commit -m "Sync with upstream, keeping my README.md unchanged" || echo "No changes to commit"
            git push origin master || echo "No changes to push"
          else
            echo "No new changes from upstream."
          fi

      # Build the Docker image only if there were changes
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push x86_64 Docker image
        if: success() && steps.merge.outputs.changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chris230291/oscam-emu:latest
